require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/bundle
    - config/puma.rb
    - config/initializers/devise.rb
    - db/schema.rb

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/environments/*
    - config/initializers/simple_form_bootstrap.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

RSpec/MultipleExpectations:
  Enabled: false
